from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List, Any
from datetime import datetime

from app.core.database import get_db
from app.api.auth import get_current_user
from app.models.user import User
from app.models.notification import NotificationRule, NotificationTemplate
from app.schemas.notification import (
    NotificationResponse, NotificationCreate, NotificationRuleCreate, 
    NotificationRuleResponse, NotificationPreferenceUpdate, NotificationPreferenceResponse,
    NotificationTemplateResponse
)
from app.notifications.engine import NotificationEngine

router = APIRouter()

@router.get("", response_model=List[NotificationResponse])
async def get_notifications(
    category: str = None, 
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    return await engine.get_user_notifications(user.id, category=category)

@router.get("/unread", response_model=List[NotificationResponse])
async def get_unread_notifications(
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    return await engine.get_user_notifications(user.id, unread_only=True)

@router.get("/history", response_model=List[NotificationResponse])
async def get_history(
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    # Just an alias for all notifications including read ones but potentially older
    engine = NotificationEngine(db)
    return await engine.get_user_notifications(user.id, limit=100)

@router.get("/preferences", response_model=NotificationPreferenceResponse)
async def get_preferences(
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    return await engine.get_user_preferences(user.id)

@router.put("/preferences", response_model=NotificationPreferenceResponse)
async def update_preferences(
    prefs: NotificationPreferenceUpdate,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    user_pref = await engine.get_user_preferences(user.id)
    
    # Update fields
    for k, v in prefs.model_dump(exclude_unset=True).items():
        setattr(user_pref, k, v)
        
    db.add(user_pref)
    await db.commit()
    await db.refresh(user_pref)
    return user_pref

@router.get("/rules", response_model=List[NotificationRuleResponse])
async def get_rules(
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    result = await db.execute(select(NotificationRule).where(NotificationRule.user_id == user.id))
    return result.scalars().all()

@router.post("/rules", response_model=NotificationRuleResponse)
async def create_rule(
    rule_data: NotificationRuleCreate,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    rule = NotificationRule(user_id=user.id, **rule_data.model_dump())
    db.add(rule)
    await db.commit()
    await db.refresh(rule)
    return rule

@router.get("/templates", response_model=List[NotificationTemplateResponse])
async def get_templates(
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    result = await db.execute(select(NotificationTemplate))
    return result.scalars().all()

@router.post("/test")
async def send_test_notification(
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    notification = await engine.create_notification(NotificationCreate(
        user_id=user.id,
        title="Test Notification",
        message="This is a test notification generated by the user.",
        category="system",
        priority="low"
    ))
    return {"status": "success", "notification_id": notification.id}

@router.post("/archive/{notification_id}")
async def archive_notification(
    notification_id: int,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    success = await engine.archive(user.id, notification_id)
    if not success:
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"status": "success"}

@router.post("/read/{notification_id}")
async def read_notification(
    notification_id: int,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    success = await engine.mark_as_read(user.id, notification_id)
    if not success:
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"status": "success"}

@router.post("/snooze/{notification_id}")
async def snooze_notification(
    notification_id: int,
    until: datetime,
    db: AsyncSession = Depends(get_db), 
    user: User = Depends(get_current_user)
):
    engine = NotificationEngine(db)
    success = await engine.snooze(user.id, notification_id, until)
    if not success:
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"status": "success"}
